### ISSUE TITLE
Moving DB off the Instance

### ISSUE THREAD

**Issue by notxt** [gt-health/PACER#18]
Hi, Michael from OCHIN

We talked way back in the spring about what it would take to move the DB off the server to an RDS instance. I can set environmental variables on the instance pretty easily, and I think if I use the [`docker-compose.yml` substitution](https://github.com/OCHININC/PACER/pull/1) then I can sub in the connection information for the RDS instance

It seems like I'd also need to remove the commands using `./wait-for-it.sh` targeting `db:5432` - ( [ie](https://github.com/gt-health/PACER/blob/master/docker-compose.yml#L18) ) - but are there any other concerns?

Like is there any data loading in `db` that would get missed? I looks like there is a [`schema_init.sql`](https://github.com/gt-health/PACER/blob/master/db/cqlstorage/schema_init.sql) and maybe some tables get seeded?

Would I just need to run these by hand if I wasn't using the `db` container?

**Comment by MikeRileyGTRI** [comment]
Hi Michael, I think this is a good idea. I don't think there's any issues here moving databases, just remember to update the ecr storage configuration, the job management system configuration, and the translate server configuration. On lines above the one you linked like [here](https://github.com/gt-health/PACER/blob/3158407b82a3e6ecb8219ec79c2b02072c1b95af/docker-compose.yml#L15).

**Comment by notxt** [comment]
@MikeRileyGTRI Nice! I'd started doing that in [this PR in the OCHIN fork](https://github.com/OCHININC/PACER/pull/2/files) but wanted to make sure it was the correct approach

I'd thought that you mentioned something about removing the calls to `cmd` calls to `wait-for-it.sh` which makes sense cause they're pointing at the db container. Is that correct?

What about `translateconcept` though? It looks like it connects to the same db but with a different [user](https://github.com/gt-health/PACER/blob/master/docker-compose.yml#L95)? Is there any reason for the different db user?

**Comment by MikeRileyGTRI** [comment]
The main reason for the wait-for-it script is to have our containers wait for the database container to be  up and running, otherwise the containers can't connect to the db in a race condition, and they don't start up right. It's hard to get the containers to block until the db is started, and this was the best, even recommended way from the docker-compose folks. So now if the db is consistently up, there's no reason for wait-for-it scripts anymore.

The translate concept service itself is a bit of a special case, it has it's own db that's deployed from a dump file, and the dump is keyed to that user, so we just create that user in the db.
